### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-backend#107]
Looks like theres been an oversight, the original docs don't make any mention of themes.

Yet on the original Atom.io Website you are able to browse and search themes.

We currently only implement `/api/themes/featured`. So this must be expanded.

Now considering the huge rework that may be needed to support every single endpoint properly, I'll propose the following.

Since we have placed such care into meeting the original spec, it would seem wrong to deviate now, and we likely could achieve full support of the Themes slug with the following.

* `/api/themes`: This would need a new endpoint and a new Database call, keep in mind packages that are themes do have a key in `package.json` with `"theme": "syntax"` or `"theme": "ui"`, so having those filtered via that key would allow us to have a full listing of themes on this endpoint.
* `/api/themes/featured`: This endpoint is already supported and requires zero work.
* `/api/themes/search`: Again this would require new handling, again filtering like done on `/api/themes`
* `/api/themes/:themeName`: Once we are into any endpoints that deal with a singular specific theme we should be safe to stop the specific handling. By having these endpoints in `main.js` simply redirect to the equivalent functions in `package_handler.js`

**Comment by confused-Techie** [comment]
On a second thought, we may want to instead of creating new endpoints, have the `packages` slug on endpoints be instead a route parameter, and we can direct the query in `main.js` from there. Since the vast majority will end up in the same place it won't be that much extra work, except we will have to build in a handler to navigating to a 404 in each request. Or alternatively, we import the `next` value in each request and pass it along if we don't have a match for that slug. Since doing this so close to the root could mean it will try and fail against many of the endpoints

**Comment by confused-Techie** [comment]
I've put up an example of how we should go about this on 17c8950ed47cf6301674649b8ef4ebb32eeb6192 where you can view how we should add the theme support, which ideally will result in the least amount of rewrites, but will need more testing.

Then for any of the single item handlers we just use the same handler for both `packages` or `themes`

**Comment by confused-Techie** [comment]
Alright, so now I've actually added the handling for `themes` and `packages` onto every single endpoint.

Now all that's needed is to actually write the functions `getThemes` and `getThemesSearch`, then of course test the nearly doubled amount of endpoints this creates

**Comment by Digitalone1** [comment]
Is this needed before v1?

**Comment by confused-Techie** [comment]
Yeah this looks about right.

I'll take a look at running this soon, after of course making a backup.

But sounds like you've got a proper understanding of it, in other words a theme would look like so

```javascript
{
  "name": "packageName",
  "theme": "theme"
```

Whereas the `theme` key would be missing in a non-theme package.

Thanks for the assistance on creating this script, I'll get to it soon

**Comment by confused-Techie** [comment]
Alright @Digitalone1 I've tried adding this script to our startup of the dev server (just to give it a dry run before being used in prod)

I did have to make one small edit based on [this](https://stackoverflow.com/a/16197615/12707685) but otherwise here is my exact code

```sql
ALTER TABLE packages ADD COLUMN package_type VARCHAR(20);

UPDATE packages
SET package_type = 'theme'
WHERE LOWER(data ->> 'theme') = 'syntax' OR LOWER(data ->> 'theme') = 'ui';

UPDATE packages
SET package_type = 'package'
WHERE package_type != 'theme';

CREATE TYPE packageType AS ENUM('package', 'theme');

ALTER TABLE packages
ALTER COLUMN package_type TYPE packageType,
ALTER COLUMN package_type SET NOT NULL;
```

But I receive the following error when running it:

```bash
error: column "package_type" cannot be cast automatically to type packagetype
```

Any ideas? Is it because there is no data inserted yet?

**Comment by confused-Techie** [comment]
Although it seems by further modifying 

`ALTER COLUMN package_type TYPE packageType USING (package_type::packageType),`

I was able to get past that step, but now receive `error: null value in column "package_type" of relation "packages" violates not-null constraint`

Which does feel more related to a lack of data? Let me see if adding a value to the inserted data to our dev instance fixes this

**Comment by confused-Techie** [comment]
Alright, the above commands have now been run against production.

@Digitalone1 I've updated our dev db as well, this will likely cause some tests to fail until we bake in this new value into our actual code as well.

But we are on the way

**Comment by Digitalone1** [comment]
@confused-Techie So when we needs themes, we search for `theme` type, but when we need packages we return both `package` and `theme` or only `package`?

**Comment by confused-Techie** [comment]
Alright, I've written some basic tests for themes and it works. The dedicated endpoints are looking good, and some basic tests to check that every `package` endpoint works for `themes` as well is good.

So looks like I can close this issue as themes are fully implemented as it's own dedicated endpoint.

Obviously there is only things to gain by additional testing and fail safes like you've been doing elsewhere. But overall we are good here
