### ISSUE TITLE
[BUG] Stargazers does not rely on users

### ISSUE THREAD

**Issue by Digitalone1** [confused-Techie/atom-backend#110]
I remember when we set up the database, we established that a user can star once a package, but the user can star many packages and a package can be starred by many users.

So we ended up with this:

```sql
CREATE TABLE stars (
    package UUID NOT NULL REFERENCES packages(pointer),
    userid INTEGER NOT NULL REFERENCES users(id),
    PRIMARY KEY (package, userid)
);
```

Then I forget about it but only now I realize this table is never used and it's bad. The stars count of a single package is the number of rows in the above table having the package pointer. Then we said "this is heavy to do every time we star a package, so let's count them once and replicate the star count in the package, so we read it faster" (and also sum it to the original stargazers). But we should also update the star table every time a star is given or removed (inserting or removing the user).

But this mechanism has never been implemented, The only thing we do is incrementing the count in the package table, which is bad since a malicious user can spam the endpoint incrementing the stars over and over.

This should be fixed before the v1 release or be disabled at the moment because it can potentially break the stargazers count.

**Comment by confused-Techie** [comment]
Since authentication still isn't in prod, we don't have to worry about disabling. But good catch on use not implementing this. We should make sure to get this in before the v1 drop

**Comment by Digitalone1** [comment]
But I suppose this needs the authentication before the implementation because we need the user to associate to the star given to the package, right?

In any case the flow for adding a star would be:

```
isStarred = checkStar(user, package);

if (isStarred) {
  return ok;
} 

return addStar(user, package);
```

To remove the star

```
isStarred = checkStar(user, package);

if (!isStarred) {
  return ok;
} 

return removeStar(user, package);
```

**Comment by confused-Techie** [comment]
> But I suppose this needs the authentication before the implementation because we need the user to associate to the star given to the package, right?
> 
> In any case the flow for adding a star would be:
> 
> ```
> isStarred = checkStar(user, package);
> 
> if (isStarred) {
>   return ok;
> } 
> 
> return addStar(user, package);
> ```
> 
> To remove the star
> 
> ```
> isStarred = checkStar(user, package);
> 
> if (!isStarred) {
>   return ok;
> } 
> 
> return removeStar(user, package);
> ```

Yes to let a user star a package they will need to be authenticated. So we can start fixing this feature now.

But essentially I'd imagine we can largely keep the flow the same, except in the functions that add and or remove stars we add the snippet you've created to additionally add it to the proper star table.

Especially since I believe we already have the user star returns assume this data exists.

**Comment by Digitalone1** [comment]
@confused-Techie yes, the snippet goes into database module where we increase and decrease stars, but those functions needs also the user identification as argument.

**Comment by confused-Techie** [comment]
> @confused-Techie yes, the snippet goes into database module where we increase and decrease stars, but those functions needs also the user identification as argument.

That sounds fine by me to add that functionality. We should try and get this in as soon as we can. And if this is something you're currently working on I'll start on making tests for all the new endpoints

**Comment by Digitalone1** [comment]
Not working on it at the moment. You can start if have time. Maybe I'll check it out

**Comment by confused-Techie** [comment]
@Digitalone1 Glad to see you're up.

So just looked at this, and we do use this table, just differently than we had originally planed. But we may be good on this front.

We have two functions 

* `database.updateStar` : Will put an entry into the star table, and will increase the star count 
* `database.updateDeleteStar`: Will remove an entry from the star table, and will decrease the star count

So while we aren't counting stars based off of the actual table itself, this still does give us a star table.

So yeah we might have jumped the gun on being worried about this one

**Comment by Digitalone1** [comment]
Oh, I didn't see, nice! 

But I think it needs an optimization. Will work on it when have time.

**Comment by confused-Techie** [comment]
> Oh, I didn't see, nice!
> 
> But I think it needs an optimization. Will work on it when have time.

This one has absolutely been a bit neglected so I'm not against improving. But yeah otherwise at least it's there.

Although does make me wonder if the functions to directly modify star counts aren't being used elsewhere if we just want to bundle them into that other function? Although maybe it's better to leave them seperate

**Comment by Digitalone1** [comment]
@confused-Techie I worked on it and ended up to bundle them. But now it's too late and even if all the tests are passing I feel it needs additional tests and a double check, so I think I will make the PR tomorrow with some additions and a more refined code.

If you have to work on the code, you can focus on other areas.

**Comment by confused-Techie** [comment]
> @confused-Techie I worked on it and ended up to bundle them. But now it's too late and even if all the tests are passing I feel it needs additional tests and a double check, so I think I will make the PR tomorrow with some additions and a more refined code.
> 
> If you have to work on the code, you can focus on other areas.

This sounds like a plan to me, we can avoid major changes until we update prod, just to make sure things are as tested as possible
