### ISSUE TITLE
Properly Implement Featured

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-backend#23]
**Is this feature Currently Implemented in any way with the upstream API Server**
- [X] Yes
- [ ] No

**Describe the solution you'd like**
To accomplish the Featured Packages, as suggested by @Spiker985, we can every week run a task, that looks at every packages download change over the week. And whichever has the highest change is used on the featured page. Maybe trunicated to 30 items. Then once the week is over this is checked again. This can be accomplished by each time its run take a snapshot of the download count, maybe under `download_count_snapshot` which contains the download count at that time, for it to be looked at again the next week. This new download_count_snapshot will need to be added when a package is installed, and pruned during show, but otherwise should be relatively easy to implement.

**Comment by Spiker985** [comment]
I would probably use two fields, `prev_download_count` and `current_download_count` or something similar

That way you just cycle current -> prev, and fill current. Bonus points if you have a calculated field for the delta, and you can use that with a weighting system to produce a mean value for use in the featured page.

Though I haven't looked at how you're storing your data, so the 3 vs 1 field may be overkill

**Comment by confused-Techie** [comment]
@Spiker985 currently a `download` count is stored, which is constant tick up or down depending if the package is installed or uninstalled. So while it may not be needed for a `current_download_count` we could store the calculated delta, but absolutely as we were talking about on the Discord Server, I do like the weighing system you're mentioning here. Although not entirely sure what youre meaning about the mean value from the weighting system. Are you meaning to basically figure out the normal distribution compared to all packages, and take the mean and up as the featured packages?

**Comment by Spiker985** [comment]
More or less.

Take this as an example: 
Package A has 0 downloads
Package B has 200 downloads

If package A gets 10 downloads, bringing the total to 10, the delta is 10, but the percent of change is 1000%

If package B gets 100 downloads, bringing the total to 300, the delta is 100, but the percent of change is 50%

Furthermore, if you take the delta, divided by the time the data occured, you get an average over time.

Package A, 10 downloads over 7 days, is an average of 1.43 downloads a day.
Package B, 100 downloads over 7 days, is an average of 14.3 downloads a day.

So you can see that depending on how you want to calculate the popularity of downloads, you may need to weigh the results.

**Comment by confused-Techie** [comment]
Thanks for taking the time to explain it thoroughly, and this does raise a fantastic point about what should be valued. 

And the count of what truly is more popular I feel would be looking at the average downloads a day. Since that may be the most agnostic way to look at it. But some more research may need to be done to determine the best method

**Comment by confused-Techie** [comment]
Since version 2.x will not occur on this repo, and instead will occur on the main Pulsar-Edit repo, I'll close this issue, and add it to the roadmap of the Backend on Pulsar.
