### ISSUE TITLE
Search Features

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-backend#40]
@Digitalone1 to allow me to merge your PR, I'll go ahead and continue the conversation of the Search Engine here. Also making it available to any other contributors that may be concerned.

The idea for the current implementation for the search engine is that in [`./src/database.js`](https://github.com/confused-Techie/atom-community-server-backend-JS/blob/main/src/database.js) `getPointerTable` would return an array of every single package name, allowing us to pass this to our custom search engine, which can then provide ranking details on each, where we could then display each package details short to the user based on this ranking.

During development there have been several search algorithm implementations played around with in [`./src/search.js`](https://github.com/confused-Techie/atom-community-server-backend-JS/blob/main/src/search.js) but in the end the current one being used is determined by what's in [`./app.yaml`](https://github.com/confused-Techie/atom-community-server-backend-JS/blob/main/app.example.yaml) which is suggested to be `lcs` or Longest Common Subsequence Algorithm. This algorithm would take a singular name of the package, and the users search term and return an index of how close the two phrases match. A `1.0` (The highest score) would indicate a perfect match, and anything lower is then used as its ranking.

I was hoping to keep the custom search still usable rather than rely on built in search from PostgreSQL, since there are already some ideas to improve this search which those ideas are available on the [Backend Project Board](https://github.com/orgs/pulsar-edit/projects/2)

But let me know if there's a better way you can think of to implement this that may improve performance

**Comment by Digitalone1** [comment]
I'm afraid this will have a big impact on performance. I hope to be wrong, but it should be tested anyway.

The problem is Javascript will have to check all records while PostgreSQL has indexes which speed up lookups.

Tomorrow I should have time to make the migration script, so we can proceed further.

**Comment by confused-Techie** [comment]
> I'm afraid this will have a big impact on performance. I hope to be wrong, but it should be tested anyway.
> 
> The problem is Javascript will have to check all records while PostgreSQL has indexes which speed up lookups.
> 
> Tomorrow I should have time to make the migration script, so we can proceed further.

That sounds like a plan to me. Got a long weekend this weekend and am hoping to make some good progress where possible. So once you have those we can start testing.

And if the performance is terrible, we may just have to go ahead and use the standard search included within the db. And worry about the new features later

**Comment by confused-Techie** [comment]
As LCS is no longer used, in favour of the built in Fuzzy Finding with PostgreSQL I'll close this issue. I still do hope to incorporate better searching, but this will be likely be a feature later on.
