### ISSUE TITLE
Implement Custom LCS Search on Database

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-backend#45]
In `./src/handlers/package_handler.js` `getPackagesSearch` it is currently using the built in search on the database. But ideally I would like to see the ability to use the custom LCS search created previously on this.

If anyone has ideas on how this can be accomplished, lets discuss them here, or a PR could be opened with a solution.

**Comment by jdramirezl** [comment]
Do we want to replace the search function altogether? Maybe the bruteforce solution would be that for each string in the packages we got from the DB simpleSearch we run the LCS function against the searched string and sort by relevance/LCS match

**Comment by confused-Techie** [comment]
> Do we want to replace the search function altogether? Maybe the bruteforce solution would be that for each string in the packages we got from the DB simpleSearch we run the LCS function against the searched string and sort by relevance/LCS match

This was actually the exact method I was thinking over on #40. But it has yet been implemented due to concerns over performance.

Although there is already a function included that would retrieve all package names to run such a brute force method against.
If you'd like to implement something like this, we can test it against the current implementation and see if theres a large performance loss.

Otherwise the LCS search itself likely doesn't need to be rewritten, just the way its being implemented from the `package_handler.js` file does.

**Comment by jdramirezl** [comment]
Just read the thread you linked and I agree with what was said about the faster indexing Postgres has. The LCS will help with a better search at a cost of performance as you said.

Will make an attempt at a solution and will look at the improved behavior/performance if any

**Comment by jdramirezl** [comment]
@confused-Techie Actually, looking more into the problem what we're trying to do is a Fuzzy Finder? 

In that case I understand that postgres (We're using this DB, right?) has an option which allows us to do  the query and the fuzzy finding at the same time, which would help us in performing the search in one query (I think, haha)

**Comment by confused-Techie** [comment]
@jdramirezl Yes we are currently using PostgreSQL.

And essentially, really just wanting to find the best way for packages to be searched. And for now it seems the most appropriate is just checking how well a users query matches the title of a package (thats because, from my research thats what Atom.io currently does.)

And with that in mind I thought that would be LCS Similarity Scores. Which worked great on JSON data (which the backend was originally written with) but failed to scale as well as hoped, and just didn't seem doable well now with SQL data. 

Currently the query for search to the Database which is [`./src/database.js simpleSearch()`](https://github.com/confused-Techie/atom-backend/blob/main/src/database.js#L866) uses a pattern like `%USER_QUERY%` allowing zero to more characters of any type on either side. But if theres any other method like fuzzy finding I'd be happy to see it, I only opened the issue as incorporating LCS because I was hoping to still use that code here.

**Comment by confused-Techie** [comment]
As we currently use PostgreSQL Fuzzy Matching, and there are no anticipated plans to implement LCS in the near future I'll close this one.
