### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by ndr-brt** [confused-Techie/atom-backend#56]
**Is your feature request related to a problem? Please describe.**
Some unit tests are broken.

**Describe the solution you'd like**
Fix them

**Comment by confused-Techie** [comment]
Thanks for going through on these broken tests. It is important to have all of these running successfully so we know our status on everything. Now that I'm back from vacation, I'm going through all of these but may take a bit of time to confirm how they run.

Thanks for the contributions!

**Comment by confused-Techie** [comment]
All tests are now passing, and we have green CI badging on the readme.

Thanks again for your efforts here, and for your contributions!
