### ISSUE TITLE
Specifying Page on Search

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-backend#58]
If a Search is executed that only has a single page of results, and the query passes `page=1` as a non-programmer would, then they are given a not found result, since the database is trying to find the 1st page of results from a zero-indexed position.

This should be resolved in a such a way to allow this to happen.

Or otherwise to investigate further with how Atom.io implements this feature and mirror that functionality.

**Comment by Digitalone1** [comment]
Can you report where is the code of that issue? Thanks.

**Comment by confused-Techie** [comment]
> Can you report where is the code of that issue? Thanks.

Whatever change fixes should likely be made in the other locations we handle pagination. But as for what the issue was originally created for `getPackagesSearch`

You can see where the `total_pages` is defined in [`./src/handlers/package_handler.js L272`](https://github.com/confused-Techie/atom-backend/blob/main/src/handlers/package_handler.js#L272).

But additional pagination occurs in `getPackages` as well

**Comment by Digitalone1** [comment]
I'm taking a look at it.

The issue might be in the `simpleSearch`?

```js
if (page !== 1) {
  offset = page * paginated_amount;
}
```

Let's set `paginated_amount` as 10. `page` is 1 by default, so for 1 you get limit 10 and offset 0. Right.

But for page 2 you get limit 10 and offset 20? Shouldn't be limit 10 and offset 10? So:

```js
if (page > 1) {
  offset = (page - 1) * paginated_amount;
}
```

**Comment by confused-Techie** [comment]
@Digitalone1 ya know I think this is it! Great find, I'll fix that today, but pretty sure that would be the root of the issue. Don't know how I didn't catch that

**Comment by Digitalone1** [comment]
@confused-Techie  This has been fixed, right?

**Comment by confused-Techie** [comment]
> @confused-Techie This has been fixed, right?

I'll probably double check in a moment, but pretty sure initial testing from what you proposed fixed this issue
