### ISSUE TITLE
Finish Tests for `GET /api/packages`

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-backend#61]
Where: `./src/test_integration/main.test.js`
What:
The tests for `Get /api/packages` have a `test.todo()` at the end, since they need additional tests to ensure the proper functionality of all supported query parameters.

**Comment by confused-Techie** [comment]
For anyone that wants to assist on this one, but is unsure how:

The test [`./src/test_integration/main.test.js` Line #110](https://github.com/confused-Techie/atom-backend/blob/c89483dcfe47df37d8e49b74cce53cce525668ca/src/tests_integration/main.test.js#L110) starts testing the endpoint `GET /api/packages`, while some aspects of this endpoint are testing, it supports additional query parameters we need to ensure are working as expected.

This means writing tests using different values of the query parameters, and making sure they all have the effect intended on the results given back to us.

To find all the query parameters supported have a look at the documentation preceding it's endpoint in [`main.js`](https://github.com/confused-Techie/atom-backend/blob/c89483dcfe47df37d8e49b74cce53cce525668ca/src/main.js#L128).

From there to find what values these query parameters are allowed to be (other than the `@valid` key in the JSDoc comments, look in [`query.js`](https://github.com/confused-Techie/atom-backend/blob/main/src/query.js).

Now finally to see what data you should be expected back, so that you can model your expectations properly, look at the [SQL data](https://github.com/confused-Techie/atom-backend/blob/main/src/dev-runner/migrations/0001-initial-migration.sql) that will be input into the test database during test runs.

If you have any questions feel free to ask.

**Comment by Digitalone1** [comment]
More or less I understood what this does, but I don't know what to add. Which specific behavior we want to reproduce?

About getting the packages I was asking myself: Should we retrieve also the removed versions? Most of the times we select only the latest version. But in `getPackagesDetails` we select everything so I wonder what's the point of the `removed` state for versions?

And if a version has all versions removed? Is it still published? We use `removePackageVersion` to flag it but shouldn't we do something to prevent the removing of all versions of a package ensuring that at least one is latest/published?

Anyway, if I should translate this in a test, I don't know how to do it. This is kind of new to me.

**Comment by confused-Techie** [comment]
> More or less I understood what this does, but I don't know what to add. Which specific behavior we want to reproduce?
> 
> About getting the packages I was asking myself: Should we retrieve also the removed versions? Most of the times we select only the latest version. But in `getPackagesDetails` we select everything so I wonder what's the point of the `removed` state for versions?
> 
> And if a version has all versions removed? Is it still published? We use `removePackageVersion` to flag it but shouldn't we do something to prevent the removing of all versions of a package ensuring that at least one is latest/published?
> 
> Anyway, if I should translate this in a test, I don't know how to do it. This is kind of new to me.

For the versions you are absolutely right. An oversight on my part. When getting all versions we need to ensure to leave out anything with a `removed` state. Since otherwise it's a pointless state. Good catch there
