### ISSUE TITLE
Track Tests Against API Endpoints

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-backend#67]
This issue serves to track what endpoints have enough tests to consider complete written for them.
While more tests on a completed endpoint is never a bad thing, this can help use semi-determine the stability of the overall application, since these tests are full integration tests of the whole codebase.

Partial Progress: ⚒

---

* [x] GET `/` 
* [x] GET ` /api/login` 
* [x] GET `/api/oauth` 
* [x] GET `/api/packages` 
* [x] POST `/api/packages`
* [x] GET `/api/packages/featured` 
* [x] GET `/api/packages/search` 
* [x] GET `/api/packages/:packageName` 
* [x] DELETE `/api/packages/:packageName` 
* [x] POST `/api/packages/:packageName/star` 
* [x] DELETE `/api/packages/:packageName/star` 
* [x] GET `/api/packages/:packageName/stargazers` 
* [x] POST `/api/packages/:packageName/versions` 
* [x] GET `/api/packages/:packageName/versions/:versionName` 
* [x] GET `/api/packages/:packageName/versions/:versionName/tarball` 
* [x] DELETE `/api/packages/:packageName/versions/:versionName` 
* [x] POST `/api/packages/:packageName/versions/:versionName/events/uninstall` 
* [x] GET `/api/themes/featured` 
* [x] GET `/api/users/:login/stars` 
* [x] GET `/api/stars` 
* [x] GET `/api/updates` - (Using Beta Version) 

---

Important Note:

Some of the endpoints here being tested are fully written, and these tests will ensure they function as expected. Which won't always be the case, so having a failing test doesn't necessarily mean you've written it wrong. But then again some of these endpoints have not been fully written, or in some cases are so early in development that they will return a `Not Supported` message. Feel free to ask any questions during this process here, or on the Pulsar-Edit Discord

**Comment by confused-Techie** [comment]
The publishing of a single package has been tested manually to work. That is "POST `/api/packages` but the automated testing is lacking. Mostly because of the difficulty in mocking all the related endpoints for an action like this

**Comment by Digitalone1** [comment]
@confused-Techie There's a miss in my previous PR

https://github.com/confused-Techie/atom-backend/blob/main/src/database.js#L817

I fixed it but we need also a test to cover the case of removing the only one remaining published/latest version which has to fail.

Something like this:
- publish a package
- add 3 more versions
- remove one "published"
- remove the "latest" (should pick a new latest among the 2 remained)
- remove one "published" to leave the package with only  the "latest" one
- remove the latest one remained (which has to fail because not allowed)

**Comment by confused-Techie** [comment]
For the last endpoint that needs to be tested `/api/packages/:packageName/versions` we will consider the tests thorough enough, until we are again able to find a proper way to automate testing on endpoints that integrate between the DB and GitHub API calls.

But for the time being the basic functionality of the tests are there, as well as many tests against the underlying Database calls, as well as the GitHub API calls. So this may be the best that they can for the time being and we will consider if complete for the sake of this issue
