### ISSUE TITLE
Prepare for 1.0 Release

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-backend#69]
Hello folks, I hope we are all excited about our soon incoming 1.0 release in time for December. 

Theres a few misc tasks that I'd hope to complete in time, so lets see if anyone is up to helping out here, I'll list each type of task below, and feel free to expand in the comments.

* [x] Remove any missed debugging `console.log()`s
* [x] Migrate `error.js` into `common_handlers.js`. Personally I feel it raises the barrier to entry by having two separate api return helpers, especially with one of these handling the logging and the other not. So ideally everything can be moved over to `common_handlers` each endpoint then gets it's logging, and everything that uses `error.js` will be moved over to `common_handler` so that `error.js` can be deleted completely.
* [ ] Pair down our code. This checkmark will realistically never be able to be clicked with certainty, but really this just means a few things.
    - [ ] Throughout the codebase, there are some ditched efforts to make our code more compact, but now themselves add to pointless bloat. These should be removed.
    - [ ] Once everything is tested and confirmed as working, as in when we are stable, I'd like to remove as many of the `database` functions as possible. A lot of these are carry-overs from the old JSON data structure.
    - [x] Any usages of `auth: req.get("Authorization")` in a handler should be replaced to `query.auth(req)` as this has built in support for error handling.
    - [ ] I'd like to implement even more numeric error codes into error handling to make reviewing the logs easier.
* [x] Migrate to new logging format, and add more logs under Trace Logging Level. By migrating our existing logs and generating many new ones, this gets us primed to enable the full feature set in prod, where we will have better visibility into errors that may be occurring on the backend, and allow a much easier debugging and issue resolution time.
* [x] Add Missing `theme` endpoints
* [x] Add Missing `users` endpoints

**Comment by Digitalone1** [comment]
>   * Once everything is tested and confirmed as working, as in when we are stable, I'd like to remove as many of the `database` functions as possible. A lot of these are carry-overs from the old JSON data structure.

I see `getPointerTable` is unused. I think it may be deleted.

**Comment by confused-Techie** [comment]
So @Digitalone1 I'm hoping to get to our v1 release this next week.

I've obviously pointed out my priorities before doing so (as well as one last missing feature I need to add) but wanted to check in with you, are there any pain points your seeing? Or anything else that we absolutely should have done before we can say we have feature parity with the upstream Atom.io backend?

**Comment by confused-Techie** [comment]
An additional point I hope to achieve, is to reach `70%` code coverage of our tests, to try and ensure to the best of our ability that we have a stable product

**Comment by Digitalone1** [comment]
> So @Digitalone1 I'm hoping to get to our v1 release this next week.
> 
> I've obviously pointed out my priorities before doing so (as well as one last missing feature I need to add) but wanted to check in with you, are there any pain points your seeing? Or anything else that we absolutely should have done before we can say we have feature parity with the upstream Atom.io backend?

I do not see pain points. But I'm not able to answer about the feature parity because  I don't know the full features of the old backend. Even if I use Atom from years, I didn't play much with packages, so I don't know what's more that the old backend was providing.

I wanted to introduce SQL views to not repeat some queries in the js code, but that's not a big priority and does not change the functionality, so we can do it the release after v1.

**Comment by Digitalone1** [comment]
> An additional point I hope to achieve, is to reach `70%` code coverage of our tests, to try and ensure to the best of our ability that we have a stable product

Sorry for my ignorance, but unfortunately I didn't understand much how codecov works. Is there a list of what's missing like codacy issues?

**Comment by confused-Techie** [comment]
Considering v1 is released, I'll go ahead and close this issue.
