### ISSUE TITLE
Add lowercase constrain on names columns

### ISSUE THREAD

**Issue by Digitalone1** [confused-Techie/atom-backend#90]
We check for lowercase names in javascript code, but this is not enough to preserve the integrity of the database since a potential issue in the code could still insert a package with uppercase characters which is not what we want.

So to prevent this we could add a [CHECK Constraint](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-check-constraint/) on the names columns.

@confused-Techie If you agree, please execute the following SQL code on the database (one line at a time).

```
ALTER TABLE names ADD CONSTRAINT lowercase_names CHECK (name = LOWER(name));
ALTER TABLE packages ADD CONSTRAINT lowercase_names CHECK (name = LOWER(name));
```

I tested them on my local database and they're working. Before I tested with `UPPER(name)` and I got 
> ERROR:  check constraint of relation "names" is violated by some row

Which is what I wanted because I inserted only lowercase names. So if you execute the code with LOWER and got the same error, it means one or more names are violating our policy of having lowercase names and this issue should be resolved.

@confused-Techie Let me know!

**Comment by confused-Techie** [comment]
Thanks so much for this, I'll run this later, and add it to the setup scripts for the database
