### ISSUE TITLE
[BUG] Unique Constraint on `versions` `semver`

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-backend#91]
Currently a duplicate version of package versions can be published, and this should be prevented on the db side

**Comment by Digitalone1** [comment]
@confused-Techie  The only way I think this could be resolved is to add a `UNIQUE` constrain on (`package`, `semver`, `status`) treble.

(`package`, `semver`) pair seems obvious, so you might wonder: Why also status?

Let's assume we publish 2.1.0, then remove it. But for some reasons we want to republish it. With only (`package`, `semver`) unique pair we can't republish it. So we need also the combination of `status` to be unique.

The issue is that if a version has been already flagged as `removed` in the past, we can't remove it another time. But this is easily avoidable refactoring `removePackageVersion` to retrieve that past version and completely delete it, then flag to existing one with `removed`.

**Comment by confused-Techie** [comment]
Thanks for the input here, and actually I remember reading about some best practices here, and it seems maybe we should go with just the `package` & `semver`, since if I download version 1.0.0 but there's some critical bug or secret within it, and the author pulls it off the store, then uploads again, if they kept the same version, I would personally never see an update and keep running this insecure, secret riddled version. 

So maybe it's best if we do add it just for the `package` and `semver` to keep from any duplicate version being published for that package?

Also on your update, you are right, we should also pass it to `query.engine` to ensure it's higher than the other one. Didn't even think of someone back publishing, but that's a great idea!

**Comment by Digitalone1** [comment]
> Thanks for the input here, and actually I remember reading about some best practices here, and it seems maybe we should go with just the `package` & `semver`, since if I download version 1.0.0 but there's some critical bug or secret within it, and the author pulls it off the store, then uploads again, if they kept the same version, I would personally never see an update and keep running this insecure, secret riddled version.
> 
> So maybe it's best if we do add it just for the `package` and `semver` to keep from any duplicate version being published for that package?

If for "the author pulls it off the store" means that version is flagged as `removed`, they can't even publish a new one of `package` & `semver` pair is unique.

**Comment by confused-Techie** [comment]
Yeah sorry, terrible terminology. But yeah if the author removes that version. So then yeah lets do those two for the treble. I'm assuming the query would be rather simple to the lower case constraint added?

**Comment by Digitalone1** [comment]
After made (`package`, `semver`, `status`) UNIQUE, we only need to add:

```sql
DELETE FROM versions
WHERE package = ${pointer} AND semver = ${semver} AND status = 'removed';
```

before [here](https://github.com/confused-Techie/atom-backend/blob/main/src/database.js#L736), so a package could be flagged as removed multiple times without violating the constrain.

Then a same version could be published, removed and republished (as `latest`).

**Comment by Digitalone1** [comment]
> Yeah sorry, terrible terminology. But yeah if the author removes that version. So then yeah lets do those two for the treble. I'm assuming the query would be rather simple to the lower case constraint added?

No, the lowercase constrain was a CHECK constrain. You need to read the documentation for the UNIQUE constrain. I will check it out.

**Comment by Digitalone1** [comment]
Here we are: https://www.tutorialsteacher.com/postgresql/unique-constraint

Something like:

```sql
ALTER TABLE table_name
ADD CONSTRAINT constraint_name
UNIQUE(column1,column2,..);
```

**Comment by confused-Techie** [comment]
Appreciate your help as always @Digitalone1, super glad at least one of us is super familiar with SQL. But perfect I'll look at adding that in then and once done will add it to our scripts as well of course

**Comment by confused-Techie** [comment]
Alright @Digitalone1 I've tried to go ahead and implement this change. But we have a few offending packages. As of now I've reached out to all the package maintainers of the offending version, and will keep you posted on how this goes. But otherwise here is a quick breakdown.

| Package Name | Offending Version | Issue |
| --- | --- | --- |
| perltidy | 0.3 | [Issue](https://github.com/kraih/atom-perltidy/issues/13) |
| perltidy | 0.2 | [Issue](https://github.com/kraih/atom-perltidy/issues/13) |
| perltidy | 0.1 | [Issue](https://github.com/kraih/atom-perltidy/issues/13) |
| atom-homestead | v0.10.0 | [Issue](https://github.com/ReeSilva/atom-homestead/issues/5) |
| doc-green-syntax | 1.0 | [Issue](https://github.com/pkrll/doc-green-syntax/issues/1) |
| language-totaljs | v0.1.2 | [Issue](https://github.com/totaljs/atom-syntax/issues/1) |
| laravel | 0.1 | [Issue](https://github.com/Cronos87/atom-laravel/issues/11) |

Also for ease of tracking purposes, I want to link to a package that had to be excluded from our database due to another issue like this.

* [swdc-atom](https://github.com/swdotcom/swdc-atom/issues/96)

**Comment by Digitalone1** [comment]
Maybe we could write a new function as semver sanitizer in git for packages that do not respect the semver 2 format, but since there's only 5 packages on thousands existing I'd say modify them manually.

Then if the author will be publishing and use the wrong format, they will get an error and will fix on their own.

**Comment by confused-Techie** [comment]
> Maybe we could write a new function as semver sanitizer in git for packages that do not respect the semver 2 format, but since there are only 5 packages on thousands existing I'd say modify them manually.
> 
> Then if the author is going to publish in the future and use the wrong format, they will get an error and will fix on their own.

Yeah I'd be more on the side of simply deny future attempts with invalid semver, and for these packages just remove the offending versions. None of these are the latest version for the packages themselves, but ideally the maintainers will get back to me with an edit they would be okay with.

**Comment by confused-Techie** [comment]
Actually one maintainer has already gotten back to me, so that's one down!

**Comment by confused-Techie** [comment]
Alright, all commands that exist in the `scripts/create_verisons_table.sql` have now been run against the production database.

We should have proper semver2 constraints, and our new virtual columns.

Thanks a ton for all the assistance on this one, glad to see it's worked
